name: SaGe experimental server
quota: 60000
max_results: 10000
graphs:
- name: sage_psql
  uri: http://localhost:8080/sparql/sage_psql
  backend: postgres
  dbname: sage
  user: sage
  password: 'sage'
-
  name: sage_psql_catalog
  uri: http://localhost:8080/sparql/sage_psql_catalog
  backend: postgres-catalog
  dbname: sage
  user: sage
  password: 'sage'
-
  name: sage_sqlite
  uri: http://localhost:8080/sparql/sage_sqlite
  backend: sqlite
  database: graphs/sage-sqlite.db
-
  name: sage_sqlite_catalog
  uri: http://localhost:8080/sparql/sage_sqlite_catalog
  backend: sqlite-catalog
  database: graphs/sage-sqlite-catalog.db
-
  name: sage_hdt
  uri: http://localhost:8080/sparql/sage_hdt
  backend: hdt-file
  file: graphs/watdiv.10M.hdt
-
  name: sage_hbase
  uri: http://localhost:8080/sparql/sage_hbase
  backend: hbase
  thrift_host: localhost
